name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} | OTP ${{ matrix.otp }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.12.x
            otp: 24
          - elixir: 1.18.x
            otp: 27
          - elixir: 1.19.x
            otp: 28
          - elixir: 1.20.x
            otp: 29
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build
      - run: mix deps.get --only test
      - run: mix lint
      - run: mix test
